<a href="https://colab.research.google.com/github/tomasiamussuri/DA_VacinacaoAL/blob/main/Vacina%C3%A7%C3%A3oCovid_19.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Dados retirados do datasus

https://opendatasus.saude.gov.br/dataset/covid-19-vacinacao/resource/301983f2-aa50-4977-8fec-cfab0806cb0b?inner_span=True

# Importando bibliotecas

In [148]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px

# Lendo arquivos

In [103]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/vacinacovid19_AL/part-00000.csv',sep = ';')

Verificação de dados

In [104]:
# Verificando tamanho da base
df.shape

(12780, 32)

In [105]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12780 entries, 0 to 12779
Data columns (total 32 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   document_id                               12780 non-null  object
 1   paciente_id                               12780 non-null  object
 2   paciente_idade                            12780 non-null  int64
 3   paciente_dataNascimento                   12780 non-null  object
 4   paciente_enumSexoBiologico                12780 non-null  object
 5   paciente_racaCor_codigo                   12780 non-null  int64
 6   paciente_racaCor_valor                    12780 non-null  object
 7   paciente_endereco_coIbgeMunicipio         12726 non-null  float64
 8   paciente_endereco_coPais                  12726 non-null  float64
 9   paciente_endereco_nmMunicipio             12726 non-null  object
 10  paciente_endereco_nmPais                  12726 non-null  object
 11  paciente_endereco_uf                      12726 non-null  object
 12  paciente_endereco_cep                     12083 non-null  object
 13  paciente_nacionalidade_enumNacionalidade  12764 non-null  object
 14  estabelecimento_valor                     12779 non-null  float64
 15  estabelecimento_razaoSocial               12779 non-null  object
 16  estalecimento_noFantasia                  12779 non-null  object
 17  estabelecimento_municipio_codigo          12779 non-null  float64
 18  estabelecimento_municipio_nome            12779 non-null  object
 19  estabelecimento_uf                        12779 non-null  object
 20  vacina_grupoAtendimento_codigo            12779 non-null  float64
 21  vacina_grupoAtendimento_nome              12756 non-null  object
 22  vacina_categoria_codigo                   12027 non-null  float64
 23  vacina_categoria_nome                     12027 non-null  object
 24  vacina_lote                               12779 non-null  object
 25  vacina_fabricante_nome                    12779 non-null  object
 26  vacina_fabricante_referencia              12747 non-null  object
 27  vacina_dataAplicacao                      12779 non-null  object
 28  vacina_descricao_dose                     12779 non-null  object
 29  vacina_codigo                             12779 non-null  float64
 30  vacina_nome                               12779 non-null  object
 31  sistema_origem                            12778 non-null  object
dtypes: float64(7), int64(2), object(23)
memory usage: 3.1+ MB

In [106]:
df.describe(include='all')

,document_id,paciente_id,paciente_idade,paciente_dataNascimento,paciente_enumSexoBiologico,paciente_racaCor_codigo,paciente_racaCor_valor,paciente_endereco_coIbgeMunicipio,paciente_endereco_coPais,paciente_endereco_nmMunicipio,...,vacina_categoria_codigo,vacina_categoria_nome,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataAplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem
count,12780,12780,12780.000000,12780,12780,12780.000000,12780,12726.000000,12726.0,12726,...,12027.000000,12027,12779,12779,12747,12779,12779,12779.000000,12779,12778
unique,12780,12758,NaN,10113,2,NaN,6,NaN,NaN,414,...,NaN,20,164,10,15,599,7,NaN,7,3
top,e5192abe-7945-4940-8fc3-9cc458ca7a76-i0b0,415d3137dbc51840d0f0d388ae3c50b842cb1163c42b30...,NaN,1975-11-08,F,NaN,PARDA,NaN,NaN,MACEIO,...,NaN,Faixa Etária,FM3884,PFIZER,Organization/00394544000851,2021-08-11,1ª Dose,NaN,COVID-19 PFIZER - COMIRNATY,Novo PNI
freq,1,2,NaN,6,7123,NaN,5004,NaN,NaN,3929,...,NaN,9236,324,5577,3346,89,5131,NaN,5577,12747
mean,NaN,NaN,39.887793,NaN,NaN,18.254069,NaN,273700.016737,10.0,NaN,...,4.546936,NaN,NaN,NaN,NaN,NaN,NaN,86.817200,NaN,NaN
std,NaN,NaN,19.545775,NaN,NaN,35.257043,NaN,23760.848286,0.0,NaN,...,12.363925,NaN,NaN,NaN,NaN,NaN,NaN,2.711069,NaN,NaN
min,NaN,NaN,3.000000,NaN,NaN,1.000000,NaN,110012.000000,10.0,NaN,...,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,85.000000,NaN,NaN
25%,NaN,NaN,24.000000,NaN,NaN,3.000000,NaN,270302.500000,10.0,NaN,...,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,85.000000,NaN,NaN
50%,NaN,NaN,39.000000,NaN,NaN,3.000000,NaN,270430.000000,10.0,NaN,...,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,87.000000,NaN,NaN
75%,NaN,NaN,54.000000,NaN,NaN,4.000000,NaN,270670.000000,10.0,NaN,...,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,87.000000,NaN,NaN
max,NaN,NaN,99.000000,NaN,NaN,99.000000,NaN,530010.000000,10.0,NaN,...,114.000000,NaN,NaN,NaN,NaN,NaN,NaN,99.000000,NaN,NaN

In [107]:
df.head(5)

,document_id,paciente_id,paciente_idade,paciente_dataNascimento,paciente_enumSexoBiologico,paciente_racaCor_codigo,paciente_racaCor_valor,paciente_endereco_coIbgeMunicipio,paciente_endereco_coPais,paciente_endereco_nmMunicipio,...,vacina_categoria_codigo,vacina_categoria_nome,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataAplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem
0,e5192abe-7945-4940-8fc3-9cc458ca7a76-i0b0,55f5a00d5628f373b5b7012df3bfa30e2cc81d43bd21e8...,26,1995-02-03,M,4,AMARELA,421480.0,10.0,RIO DO SUL,...,2.0,Faixa Etária,FF8842,PFIZER,Organization/00394544000851,2021-10-06,2ª Dose,87.0,COVID-19 PFIZER - COMIRNATY,Novo PNI
1,b1dede4b-98d3-4100-9fa1-5b86bad8118c-i0b0,a821bd562732e4fe4a57dbf1842bfff6fe5f4629c573ee...,42,1979-07-06,F,99,SEM INFORMACAO,261160.0,10.0,RECIFE,...,2.0,Faixa Etária,205H21A,JANSSEN,Organization/30587,2022-01-04,Reforço,88.0,COVID-19 JANSSEN - Ad26.COV2.S,Novo PNI
2,e51bf7d3-9bf6-464d-a90c-72a48fbb7ec0-i0b0,123e439bc6c2864c4cb8cb7cbac3dea3068c6686618320...,36,1985-08-04,M,3,PARDA,270100.0,10.0,BOCA DA MATA,...,2.0,Faixa Etária,210354,SINOVAC/BUTANTAN,Organization/61189445000156,2021-08-25,2ª Dose,86.0,COVID-19 SINOVAC/BUTANTAN - CORONAVAC,Novo PNI
3,b1dfcef0-0523-4b7d-9afb-0f3bfcac9985-i0b0,e413e885f32bdc1e1fe1ee4768c5c4324edbdc9e315ffe...,24,1996-12-05,M,3,PARDA,270510.0,10.0,MATRIZ DE CAMARAGIBE,...,8.0,Trabalhadores da Educação,213VCD027Z,ASTRAZENECA/FIOCRUZ,Organization/33781055000135,2021-06-02,1ª Dose,85.0,COVID-19 ASTRAZENECA/FIOCRUZ - COVISHIELD,Novo PNI
4,e523e502-2640-4668-ab4f-ef5505ec4681-i0b0,406a7cd0145d6a877089e588d105483c14f5f4f2410389...,37,1983-10-06,M,3,PARDA,270570.0,10.0,OLHO D'AGUA DAS FLORES,...,2.0,Faixa Etária,211A21A,JANSSEN,Organization/00394544000851,2021-07-17,Dose,88.0,COVID-19 JANSSEN - Ad26.COV2.S,Novo PNI

In [108]:
# Verificando valores nulos da base
df.isnull().sum()

document_id                                   0
paciente_id                                   0
paciente_idade                                0
paciente_dataNascimento                       0
paciente_enumSexoBiologico                    0
paciente_racaCor_codigo                       0
paciente_racaCor_valor                        0
paciente_endereco_coIbgeMunicipio            54
paciente_endereco_coPais                     54
paciente_endereco_nmMunicipio                54
paciente_endereco_nmPais                     54
paciente_endereco_uf                         54
paciente_endereco_cep                       697
paciente_nacionalidade_enumNacionalidade     16
estabelecimento_valor                         1
estabelecimento_razaoSocial                   1
estalecimento_noFantasia                      1
estabelecimento_municipio_codigo              1
estabelecimento_municipio_nome                1
estabelecimento_uf                            1
vacina_grupoAtendimento_codigo                1
vacina_grupoAtendimento_nome                 24
vacina_categoria_codigo                     753
vacina_categoria_nome                       753
vacina_lote                                   1
vacina_fabricante_nome                        1
vacina_fabricante_referencia                 33
vacina_dataAplicacao                          1
vacina_descricao_dose                         1
vacina_codigo                                 1
vacina_nome                                   1
sistema_origem                                2
dtype: int64

In [144]:
# Total de Vacinas x Fabricante
#fabricante = df.groupby(['vacina_fabricante_nome']).agg({'document_id': 'count'})
fabricante = df['vacina_fabricante_nome'].value_counts()
display(fabricante)

PFIZER                    5577
ASTRAZENECA/FIOCRUZ       3620
SINOVAC/BUTANTAN          2451
Pendente Identificação     414
ASTRAZENECA                313
JANSSEN                    267
PFIZER - PEDI?TRICA         95
SINOVAC                     18
PFIZER - PEDIÁTRICA         14
Pendente Identifica??o      10
Name: vacina_fabricante_nome, dtype: int64

In [145]:
fabricante.index

Index(['PFIZER', 'ASTRAZENECA/FIOCRUZ', 'SINOVAC/BUTANTAN',
       'Pendente Identificação', 'ASTRAZENECA', 'JANSSEN',
       'PFIZER - PEDI?TRICA', 'SINOVAC', 'PFIZER - PEDIÁTRICA',
       'Pendente Identifica??o'],
      dtype='object')

In [146]:
fabricante.values

array([5577, 3620, 2451,  414,  313,  267,   95,   18,   14,   10])

In [147]:
#Gráfico Pizza - Fabricante
px.pie(fabricante, names=fabricante.index, values=fabricante.values)

In [121]:
# Quantidade de vacinados por município
df.groupby(['estabelecimento_municipio_nome']).agg({'document_id': 'count'})

                                document_id
estabelecimento_municipio_nome
AGUA BRANCA                             100
ANADIA                                   64
ARAPIRACA                               875
ATALAIA                                 134
BARRA DE SANTO ANTONIO                   42
...                                     ...
TAQUARANA                                47
TEOTONIO VILELA                         136
TRAIPU                                   95
UNIAO DOS PALMARES                      201
VICOSA                                  104

[102 rows x 1 columns]

In [111]:
# % de Vacinas por Sexo
df.paciente_enumSexoBiologico.value_counts(normalize=True)

F    0.557355
M    0.442645
Name: paciente_enumSexoBiologico, dtype: float64

In [124]:
# Quantidade de vacinados por Sexo
df_sexo = df.groupby(['paciente_enumSexoBiologico']).agg({'document_id': 'count'}).reset_index()
display(df_sexo)

  paciente_enumSexoBiologico  document_id
0                          F         7123
1                          M         5657

In [139]:
# Gráfico de barras - Sexo
px.bar(df_sexo, x='paciente_enumSexoBiologico', y='document_id', color='paciente_enumSexoBiologico', barmode='group')

In [137]:
# Quantidade de vacinados por município
df_mun_idade_vacina = df.groupby(['estabelecimento_municipio_nome','paciente_idade','vacina_fabricante_nome'], sort=False).count().reset_index()
display(df_mun_idade_vacina)

,estabelecimento_municipio_nome,paciente_idade,vacina_fabricante_nome,document_id,paciente_id,paciente_dataNascimento,paciente_enumSexoBiologico,paciente_racaCor_codigo,paciente_racaCor_valor,paciente_endereco_coIbgeMunicipio,...,vacina_grupoAtendimento_nome,vacina_categoria_codigo,vacina_categoria_nome,vacina_lote,vacina_fabricante_referencia,vacina_dataAplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem
0,BATALHA,26,PFIZER,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
1,MACEIO,42,JANSSEN,5,5,5,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5
2,BOCA DA MATA,36,SINOVAC/BUTANTAN,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
3,MATRIZ DE CAMARAGIBE,24,ASTRAZENECA/FIOCRUZ,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
4,OLHO D'AGUA DAS FLORES,37,JANSSEN,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6048,ATALAIA,65,SINOVAC/BUTANTAN,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
6049,IBATEGUARA,33,PFIZER,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
6050,POCO DAS TRINCHEIRAS,16,PFIZER,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
6051,ATALAIA,36,SINOVAC/BUTANTAN,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
6052,PINDOBA,65,SINOVAC/BUTANTAN,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1